//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assignment1.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to Microsoft Exchange. (c) 2010 Microsoft Corporation. All rights reserved..
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect login credentials!.
        /// </summary>
        public static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful!.
        /// </summary>
        public static string LoginOK {
            get {
                return ResourceManager.GetString("LoginOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a public or shared computer.
        /// </summary>
        public static string Radio1 {
            get {
                return ResourceManager.GetString("Radio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option if you use Outlook Web App on a public computer. Be sure to sign out when you&apos;ve finished and close all windows to end your session..
        /// </summary>
        public static string Radio1Expand {
            get {
                return ResourceManager.GetString("Radio1Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a private computer.
        /// </summary>
        public static string Radio2 {
            get {
                return ResourceManager.GetString("Radio2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option if you&apos;re the only person who uses this computer. Your server will allow a longer period of inactivity before signing you out..
        /// </summary>
        public static string Radio2Expand {
            get {
                return ResourceManager.GetString("Radio2Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: By selecting this option, you confirm that this computer complies with your organization&apos;s security policy..
        /// </summary>
        public static string Radio2Warning {
            get {
                return ResourceManager.GetString("Radio2Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security ( hide explanation ).
        /// </summary>
        public static string SecurityHide {
            get {
                return ResourceManager.GetString("SecurityHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security ( show explanation ) .
        /// </summary>
        public static string SecurityShow {
            get {
                return ResourceManager.GetString("SecurityShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SigninButton {
            get {
                return ResourceManager.GetString("SigninButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address:.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the light version of Outlook Web App.
        /// </summary>
        public static string WebAppLight {
            get {
                return ResourceManager.GetString("WebAppLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatever this is in english, I could not get the proper text since it is not easy to change the language of the Outlook Web App login page..
        /// </summary>
        public static string WebAppLightExpand {
            get {
                return ResourceManager.GetString("WebAppLightExpand", resourceCulture);
            }
        }
    }
}
